### ISSUE TITLE
Pack tool not creating Mood / Corruption file

### ISSUE THREAD

**Issue by EdgeAnon** [araten10/EdgewarePlusPlus#107]
Hey, I am trying to make a pack using Pack Tool rather than overwriting existing pack files manually (as I usually do).

I set up everything and no matter what I try Moods, Captions and Corruption fail to generate - output from the tool and the 'pack' file attached bellow.

i did try checking the code, removing and adding symbols, lines, ect
I did try to check Pack tool code for any clues but I cannot figure it out.

I am on the latest python version provided with EW13 and Pack tool was re-downloaded 1-2 days ago just to check if there was some issue with it being outdated.
I have similar error when using default Pack.yml too

I am clueless as to what might be the cause.

![Screenshot 2024-10-21 172352](https://github.com/user-attachments/assets/bf7df68c-9a67-49ae-ac4e-1c0ca35d6827)
[pack - txt.txt](https://github.com/user-attachments/files/17464172/pack.-.txt.txt)

**Comment by LewdDevelopment** [comment]
You left the lines in the `prefixes`, `moods`, and `levels` commented. E.g., rather than
```yaml
  moods:
  # - name: "Subtle"
  #   weight: 100
  #   prompts:
  #     - "I am just curious"
  #     - "What could it mean?"
```
it should be:
```yaml
  moods:
    - name: "Subtle"
      weight: 100
      prompts:
        - "I am just curious"
        - "What could it mean?"
```
As an exception, in the corruption level list though, the "Level N" lines are intended as just comments, so that should be:
```yaml
  levels:
    # Level 1
    - add-moods:
        - "Subtle"
      remove-moods:
      wallpaper: "WppSubtle.jpg"
```
This has been a point of confusion before, so I updated the examples in `default_pack.yml` to reflect what they should look like in an actual pack. Hope this helps!
